
/* Frozen modules initializer
 *
 * Frozen modules are written to header files by Programs/_freeze_module.
 * These files are typically put in Python/frozen_modules/.  Each holds
 * an array of bytes named "_Py_M__<module>", which is used below.
 *
 * These files must be regenerated any time the corresponding .pyc
 * file would change (including with changes to the compiler, bytecode
 * format, marshal format).  This can be done with "make regen-frozen".
 * That make target just runs Tools/build/freeze_modules.py.
 *
 * The freeze_modules.py script also determines which modules get
 * frozen.  Update the list at the top of the script to add, remove,
 * or modify the target modules.  Then run the script
 * (or run "make regen-frozen").
 *
 * The script does the following:
 *
 * 1. run Programs/_freeze_module on the target modules
 * 2. update the includes and _PyImport_FrozenModules[] in this file
 * 3. update the FROZEN_FILES variable in Makefile.pre.in
 * 4. update the per-module targets in Makefile.pre.in
 * 5. update the lists of modules in PCbuild/_freeze_module.vcxproj and
 *    PCbuild/_freeze_module.vcxproj.filters
 *
 * (Note that most of the data in this file is auto-generated by the script.)
 *
 * Those steps can also be done manually, though this is not recommended.
 * Expect such manual changes to be removed the next time
 * freeze_modules.py runs.
 * */

/* In order to test the support for frozen modules, by default we
   define some simple frozen modules: __hello__, __phello__ (a package),
   and __phello__.spam.  Loading any will print some famous words... */

#include "Python.h"
#include "pycore_import.h"

#include <stdbool.h>

/* Includes for frozen modules: */
#include "Python/frozen_modules/importlib._bootstrap.h"
#include "Python/frozen_modules/importlib._bootstrap_external.h"
#include "Python/frozen_modules/zipimport.h"

#include "Python/frozen_modules/_collections_abc.h"
#include "Python/frozen_modules/_sitebuiltins.h"
#include "Python/frozen_modules/abc.h"
#include "Python/frozen_modules/codecs.h"
#include "Python/frozen_modules/frozen_only.h"
#include "Python/frozen_modules/genericpath.h"
#include "Python/frozen_modules/importlib.machinery.h"
#include "Python/frozen_modules/importlib.util.h"
#include "Python/frozen_modules/io.h"
#include "Python/frozen_modules/ntpath.h"
#include "Python/frozen_modules/os.h"
#include "Python/frozen_modules/posixpath.h"
#include "Python/frozen_modules/runpy.h"
#include "Python/frozen_modules/site.h"
#include "Python/frozen_modules/stat.h"

#include "Python/frozen_modules/__hello__.h"
#include "Python/frozen_modules/__phello__.h"
#include "Python/frozen_modules/__phello__.ham.eggs.h"
#include "Python/frozen_modules/__phello__.ham.h"
#include "Python/frozen_modules/__phello__.spam.h"

/* End includes */



static const struct _frozen bootstrap_modules[] = {
    {"_frozen_importlib", _Py_M__importlib__bootstrap, (int)sizeof(_Py_M__importlib__bootstrap)},
    {"_frozen_importlib_external", _Py_M__importlib__bootstrap_external, (int)sizeof(_Py_M__importlib__bootstrap_external)},
    {"zipimport", _Py_M__zipimport, (int)sizeof(_Py_M__zipimport)},
    {0, 0, 0} /* bootstrap sentinel */
};


#define MOD(name) { #name, _Py_M__##name, (int)sizeof( _Py_M__##name) }
#define MOD_ALIAS(alias, name) { #alias, _Py_M__##name, (int)sizeof( _Py_M__##name) }

static const struct _frozen stdlib_modules[] = {
    /* stdlib - startup, without site (python -S) */
    MOD(abc),
    MOD(codecs),
    MOD(io),

    /* stdlib - startup, with site */
    MOD(_collections_abc),
    MOD(_sitebuiltins),
    MOD(genericpath),
    MOD(ntpath),
    MOD(posixpath),
    MOD_ALIAS(os.path, posixpath),
    MOD(os),
    MOD(site),
    MOD(stat),
    MOD_ALIAS(importlib.util, importlib_util),
    MOD_ALIAS(importlib.machinery, importlib_machinery),
    MOD(runpy),
    {0, 0, 0} /* stdlib sentinel */
};

static const struct _frozen test_modules[] = {
    MOD(__hello__),
    MOD_ALIAS(__hello_alias__, __hello__),
    MOD_ALIAS(__phello_alias__, __hello__),
    MOD_ALIAS(__phello_alias__.spam, __hello__),
    MOD(__phello__),
    MOD_ALIAS(__phello__.__init__, __phello__),
    MOD_ALIAS(__phello__.ham, __phello__),
    MOD_ALIAS(__phello__.ham.__init__, __phello__),
    MOD_ALIAS(__phello__.ham.eggs, __phello___ham_eggs),
    MOD_ALIAS(__phello__.spam, __phello___spam),
    MOD_ALIAS(__hello_only__, frozen_only),
    {0, 0, 0} /* test sentinel */
};

const struct _frozen *_PyImport_FrozenBootstrap = bootstrap_modules;
const struct _frozen *_PyImport_FrozenStdlib = stdlib_modules;
const struct _frozen *_PyImport_FrozenTest = test_modules;

static const struct _module_alias aliases[] = {
    {"_frozen_importlib", "importlib._bootstrap"},
    {"_frozen_importlib_external", "importlib._bootstrap_external"},
    {"os.path", "posixpath"},
    {"__hello_alias__", "__hello__"},
    {"__phello_alias__", "__hello__"},
    {"__phello_alias__.spam", "__hello__"},
    {"__phello__.__init__", "<__phello__"},
    {"__phello__.ham.__init__", "<__phello__.ham"},
    {"__hello_only__", NULL},
    {0, 0} /* aliases sentinel */
};
const struct _module_alias *_PyImport_FrozenAliases = aliases;


/* Embedding apps may change this pointer to point to their favorite
   collection of frozen modules: */

const struct _frozen *PyImport_FrozenModules = NULL;


